FROM public.ecr.aws/lambda/python@sha256:d81866a7ab07fb9e725dd4610076462f6eb3b86f2ff771f41bd123127eed6976 as build
RUN yum install -y unzip tar wget xz && \
    curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip" && \
    curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1047731%2Fchrome-linux.zip?alt=media" && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/chrome-linux.zip -d /opt/


FROM public.ecr.aws/lambda/python@sha256:d81866a7ab07fb9e725dd4610076462f6eb3b86f2ff771f41bd123127eed6976
RUN yum -y update
RUN yum -y install gcc44 gcc-c++ libgcc44 cmake –y
RUN yum -y install bzip2 xorg-x11-server-Xvfb wget tar xz make
RUN yum -y install gcc gcc-c++ make autoconf libtool
RUN yum -y install atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel
RUN yum -y install gcc-c++ libmad libmad-devel libid3tag libid3tag-devel lame lame-devel flac-devel libvorbis-devel

RUN pip install pymysql
RUN pip install unicaps
RUN pip install pandas
RUN pip install requests
RUN pip install json
RUN pip install re
RUN pip install pymysql
RUN pip install numpy
RUN pip install os
RUN pip install logging
RUN pip install datetime
RUN pip install time
RUN pip install dateutil.relativedelta

COPY --from=build /opt/chrome-linux /opt/chrome
COPY --from=build /opt/chromedriver /opt/
COPY main.py ./
CMD [ "main.handler" ]